### 获取token
POST http://localhost:8088/oauth/token
Content-Type: application/json

{
  "username": "test",
  "password": "123456"
}

### 刷新token,切换用户
POST http://localhost:8088/oauth/refresh
Content-Type: application/json

{
  "usercode": "jsjfff",
  "refresh_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50Q29kZSI6bnVsbCwiZW50TmFtZSI6bnVsbCwiYWNjb3VudE5hbWUiOiJ0ZXN0IiwidXNlcl9uYW1lIjoidGVzdCIsInVzZXJOYW1lIjpudWxsLCJ1c2VyQ29kZSI6bnVsbCwiY2xpZW50X2lkIjoiaWVycCIsImVudENvZGUiOm51bGwsInNjb3BlIjpbImFsbCJdLCJhdGkiOiIwZTRhNWNlNS1iNmM4LTRhMGYtYTY2ZS02OWY5Yzc1NWU3MDciLCJzZXJ2ZXJUaW1lIjoxNjUyMjM2NjgwLCJleHAiOjE2NTIzMjMwODAsImp0aSI6IjU2MTMxMzJiLTUzNGUtNGIxMy1hNDU5LTEyZDk0NjMwNzRmOSJ9.PvvXX2hixBQQbXPmnfUNXKQ9M6SeIVYT7CuMI2lQvVQkkywSAcfZNVjPf2ZjaeTTPoQD6TCIMkt3fdUAbzFYWsO3GU46QJz9z3xPPT9bQJxZ_kMzeo0IjEOpVzaXQHx9PE7gm7dv8Jz0pab4nCHQVpFwar8DUia1LAuaXPjNIth-bAVeCS6YcC_JJXWsdl3_bvj8hh40BXD9u8Of640byU0QnCGz9U1utUUyxeMLQ_FYgqeqCwT1e23BRNh-IIYZRjndcxIbAPfUt-lm-nGqNf4Wbk8LUVeRcE3qS-qKujz30jkZwIwy5_Er8-yNxf1-MuWeGvzzcp7XQ8pE4qocqQ"
}

### 注销token 方式一
GET http://localhost:8088/oauth/revoke
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50Q29kZSI6bnVsbCwiZW50TmFtZSI6bnVsbCwiZW50Q29kZSI6bnVsbCwiYWNjb3VudE5hbWUiOiJqc2pmZmYwMDEiLCJ1c2VyX25hbWUiOiJqc2pmZmYwMDEiLCJzY29wZSI6WyJhbGwiXSwic2VydmVyVGltZSI6MTY1MjIzNjcxMCwiZXhwIjoxNjUyMjQzOTEwLCJ1c2VyTmFtZSI6bnVsbCwianRpIjoiYzIzODE0ZjgtNmZhMy00MDEwLWE2OWYtZDc5ZTg0NjNkNWY2IiwidXNlckNvZGUiOm51bGwsImNsaWVudF9pZCI6ImllcnAifQ.O3hatAkdLcdqCaYZ7s6vn4auMNOeCoKg6onA9AWF6TPG9MlAR81H3Setp9PyYjyWhDmjiePjhYTkgoGvc92RX9tpd8V7Nwyxr3je_zvNGmoWvW-bly3PxtY_IjeRWAnLL2nsnPMk4WI5fqORH0nvW2qLLng_cXGJd1q7X1OIH6pxewG2P636n1yXEFFuOF-WpEL-tI2rBagKAl-WnBn5PqTwcqMv7m6TnjIDp5DWevnlG8uJ_DaTKGeu7FlHOCdLZ0zn1B8hxs12wmKYpoBkmIJe8MOvYLECoSuuW1croP-mxASNXJGIXY5alhAuZci8ZMPg68qFttEoimViiQqRbg
Accept: application/json

### 注销token 方式二
GET http://localhost:8088/oauth/revoke?access_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50Q29kZSI6bnVsbCwiZW50TmFtZSI6bnVsbCwiZW50Q29kZSI6bnVsbCwiYWNjb3VudE5hbWUiOiJqc2pmZmYwMDEiLCJ1c2VyX25hbWUiOiJqc2pmZmYwMDEiLCJzY29wZSI6WyJhbGwiXSwic2VydmVyVGltZSI6MTY1MjIzNjcxMCwiZXhwIjoxNjUyMjQzOTEwLCJ1c2VyTmFtZSI6bnVsbCwianRpIjoiYzIzODE0ZjgtNmZhMy00MDEwLWE2OWYtZDc5ZTg0NjNkNWY2IiwidXNlckNvZGUiOm51bGwsImNsaWVudF9pZCI6ImllcnAifQ.O3hatAkdLcdqCaYZ7s6vn4auMNOeCoKg6onA9AWF6TPG9MlAR81H3Setp9PyYjyWhDmjiePjhYTkgoGvc92RX9tpd8V7Nwyxr3je_zvNGmoWvW-bly3PxtY_IjeRWAnLL2nsnPMk4WI5fqORH0nvW2qLLng_cXGJd1q7X1OIH6pxewG2P636n1yXEFFuOF-WpEL-tI2rBagKAl-WnBn5PqTwcqMv7m6TnjIDp5DWevnlG8uJ_DaTKGeu7FlHOCdLZ0zn1B8hxs12wmKYpoBkmIJe8MOvYLECoSuuW1croP-mxASNXJGIXY5alhAuZci8ZMPg68qFttEoimViiQqRbg
Accept: application/json

### 测试白名单
GET http://localhost:8088/test
Accept: application/json

### 测试白名单，附带用户身份
GET http://localhost:8088/test?access_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50Q29kZSI6bnVsbCwiZW50TmFtZSI6bnVsbCwiZW50Q29kZSI6bnVsbCwiYWNjb3VudE5hbWUiOiJqc2pmZmYwMDEiLCJ1c2VyX25hbWUiOiJqc2pmZmYwMDEiLCJzY29wZSI6WyJhbGwiXSwic2VydmVyVGltZSI6MTY1MjIzNjcxMCwiZXhwIjoxNjUyMjQzOTEwLCJ1c2VyTmFtZSI6bnVsbCwianRpIjoiYzIzODE0ZjgtNmZhMy00MDEwLWE2OWYtZDc5ZTg0NjNkNWY2IiwidXNlckNvZGUiOm51bGwsImNsaWVudF9pZCI6ImllcnAifQ.O3hatAkdLcdqCaYZ7s6vn4auMNOeCoKg6onA9AWF6TPG9MlAR81H3Setp9PyYjyWhDmjiePjhYTkgoGvc92RX9tpd8V7Nwyxr3je_zvNGmoWvW-bly3PxtY_IjeRWAnLL2nsnPMk4WI5fqORH0nvW2qLLng_cXGJd1q7X1OIH6pxewG2P636n1yXEFFuOF-WpEL-tI2rBagKAl-WnBn5PqTwcqMv7m6TnjIDp5DWevnlG8uJ_DaTKGeu7FlHOCdLZ0zn1B8hxs12wmKYpoBkmIJe8MOvYLECoSuuW1croP-mxASNXJGIXY5alhAuZci8ZMPg68qFttEoimViiQqRbg
Accept: application/json

### 获取公钥
GET http://localhost:8088/oauth/token_key
Accept: application/json