spring.application.name=mvc-rest-reactive-spring-boot-sample

# eureka
# ??15???eureka???????
eureka.client.registry-fetch-interval-seconds=30
eureka.client.service-url.defaultZone=http://10.96.169.232:3030/eureka/
eureka.instance.instance-id=${spring.application.name}:${spring.cloud.client.ip-address}:${random.value}
eureka.instance.prefer-ip-address=true
eureka.instance.metadataMap.instance-id=${spring.application.name}:${random.value}
encrypt.fail-on-error=false
