<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <packaging>pom</packaging>
    <modules>
        <module>mybatis-spring-boot-autoconfigure</module>
        <module>mybatis-spring-boot-starter</module>
        <module>mybatis-spring-boot-sample</module>
        <module>job-spring-boot-starter</module>
        <module>job-spring-boot-autoconfigure</module>
        <module>job-spring-boot-sample</module>
        <module>sentinel-zuul-spring-boot-starter</module>
        <module>sentinel-zuul-spring-boot-autoconfigure</module>
        <module>sentinel-spring-boot-autoconfigure</module>
        <module>sentinel-spring-boot-starter</module>
        <module>sentinel-gateway-spring-boot-autoconfigure</module>
        <module>sentinel-gateway-spring-boot-starter</module>
        <module>nacos-config-spring-boot-starter</module>
        <module>nacos-config-spring-boot-autoconfigure</module>
        <module>nacos-discovery-spring-boot-autoconfigure</module>
        <module>nacos-discovery-spring-boot-starter</module>
        <module>nacos-config-discovery-spring-boot-sample</module>
        <module>jpa-spring-boot-autoconfigure</module>
        <module>jpa-spring-boot-starter</module>
        <module>jpa-spring-boot-sample</module>
        <module>audit-spring-boot-autoconfigure</module>
        <module>rabbit-spring-boot-autoconfigure</module>
        <module>rabbit-spring-boot-starter</module>
        <module>websocket-spring-boot-autoconfigure</module>
        <module>websocket-spring-boot-starter</module>
        <module>rabbit-spring-boot-sample</module>
        <module>audit-spring-boot-starter</module>
        <module>audit-spring-boot-sample</module>
        <module>doc-spring-boot-autoconfigure</module>
        <module>doc-spring-boot-sample</module>
        <module>doc-spring-boot-starter</module>
        <module>mvc-rest-spring-boot-autoconfigure</module>
        <module>mvc-rest-spring-boot-starter</module>
        <module>mvc-rest-spring-boot-sample</module>
        <module>lock-spring-boot-autoconfigure</module>
        <module>lock-spring-boot-starter</module>
        <module>lock-spring-boot-sample</module>
        <module>customizer-spring-boot-autoconfigure</module>
        <module>customizer-spring-boot-starter</module>
        <module>customizer-spring-boot-sample</module>
        <module>redis-spring-boot-autoconfigure</module>
        <module>redis-spring-boot-sample</module>
        <module>redis-spring-boot-starter</module>
    </modules>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.11.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.yj2025</groupId>
    <artifactId>yj2025-spring-boot-parent</artifactId>
    <version>1.1.1-SNAPSHOT</version>
    <properties>
        <java.version>1.8</java.version>
        <spring-cloud.version>Hoxton.SR11</spring-cloud.version>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <job.version>1.1.1-SNAPSHOT</job.version>
        <jpa.version>1.1.1-SNAPSHOT</jpa.version>
        <mybatis.version>1.1.1-SNAPSHOT</mybatis.version>
        <nacos-config.version>1.1.1-SNAPSHOT</nacos-config.version>
        <nacos-discovery.version>1.1.1-SNAPSHOT</nacos-discovery.version>
        <sentinel-gateway.version>1.1.1-SNAPSHOT</sentinel-gateway.version>
        <sentinel-micro.version>1.1.1-SNAPSHOT</sentinel-micro.version>
        <sentinel-zuul.version>1.1.1-SNAPSHOT</sentinel-zuul.version>
        <rabbit.version>1.1.1-SNAPSHOT</rabbit.version>
        <websocket.version>1.1.1-SNAPSHOT</websocket.version>
        <audit.version>1.1.1-SNAPSHOT</audit.version>
        <doc.version>1.1.1-SNAPSHOT</doc.version>
        <mvc-rest.version>1.1.1-SNAPSHOT</mvc-rest.version>
        <lock.version>1.1.1-SNAPSHOT</lock.version>
        <override.version>1.1.1-SNAPSHOT</override.version>
    </properties>


    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.yj2025</groupId>
                <artifactId>business-dependencies</artifactId>
                <version>1.1.9</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- starter 基础依赖 -->
            <!-- job -->
            <dependency>
                <groupId>com.yj2025</groupId>
                <artifactId>job-spring-boot-autoconfigure</artifactId>
                <version>${job.version}</version>
            </dependency>
            <dependency>
                <groupId>com.yj2025</groupId>
                <artifactId>job-spring-boot-starter</artifactId>
                <version>${job.version}</version>
            </dependency>

            <!-- jpa -->
            <dependency>
                <groupId>com.yj2025</groupId>
                <artifactId>jpa-spring-boot-autoconfigure</artifactId>
                <version>${jpa.version}</version>
            </dependency>
            <dependency>
                <groupId>com.yj2025</groupId>
                <artifactId>jpa-spring-boot-starter</artifactId>
                <version>${jpa.version}</version>
            </dependency>

            <!-- mybatis -->
            <dependency>
                <groupId>com.yj2025</groupId>
                <artifactId>mybatis-spring-boot-autoconfigure</artifactId>
                <version>${mybatis.version}</version>
            </dependency>
            <dependency>
                <groupId>com.yj2025</groupId>
                <artifactId>mybatis-spring-boot-starter</artifactId>
                <version>${mybatis.version}</version>
            </dependency>

            <!-- nacos config -->
            <dependency>
                <groupId>com.yj2025</groupId>
                <artifactId>nacos-config-spring-boot-autoconfigure</artifactId>
                <version>${nacos-config.version}</version>
            </dependency>
            <dependency>
                <groupId>com.yj2025</groupId>
                <artifactId>nacos-config-spring-boot-starter</artifactId>
                <version>${nacos-config.version}</version>
            </dependency>

            <!-- nacos discovery -->
            <dependency>
                <groupId>com.yj2025</groupId>
                <artifactId>nacos-discovery-spring-boot-autoconfigure</artifactId>
                <version>${nacos-discovery.version}</version>
            </dependency>
            <dependency>
                <groupId>com.yj2025</groupId>
                <artifactId>nacos-discovery-spring-boot-starter</artifactId>
                <version>${nacos-discovery.version}</version>
            </dependency>

            <!-- sentinel gateway -->
            <dependency>
                <groupId>com.yj2025</groupId>
                <artifactId>sentinel-gateway-spring-boot-autoconfigure</artifactId>
                <version>${sentinel-gateway.version}</version>
            </dependency>
            <dependency>
                <groupId>com.yj2025</groupId>
                <artifactId>sentinel-gateway-spring-boot-starter</artifactId>
                <version>${sentinel-gateway.version}</version>
            </dependency>

            <!-- sentinel micro service -->
            <dependency>
                <groupId>com.yj2025</groupId>
                <artifactId>sentinel-spring-boot-autoconfigure</artifactId>
                <version>${sentinel-micro.version}</version>
            </dependency>
            <dependency>
                <groupId>com.yj2025</groupId>
                <artifactId>sentinel-spring-boot-starter</artifactId>
                <version>${sentinel-micro.version}</version>
            </dependency>

            <!-- sentinel zuul -->
            <dependency>
                <groupId>com.yj2025</groupId>
                <artifactId>sentinel-zuul-spring-boot-autoconfigure</artifactId>
                <version>${sentinel-zuul.version}</version>
            </dependency>
            <dependency>
                <groupId>com.yj2025</groupId>
                <artifactId>sentinel-zuul-spring-boot-starter</artifactId>
                <version>${sentinel-zuul.version}</version>
            </dependency>

            <!-- rabbit -->
            <dependency>
                <groupId>com.yj2025</groupId>
                <artifactId>rabbit-spring-boot-autoconfigure</artifactId>
                <version>${rabbit.version}</version>
            </dependency>
            <dependency>
                <groupId>com.yj2025</groupId>
                <artifactId>rabbit-spring-boot-starter</artifactId>
                <version>${rabbit.version}</version>
            </dependency>

            <!-- redis -->
            <dependency>
                <groupId>com.yj2025</groupId>
                <artifactId>redis-spring-boot-autoconfigure</artifactId>
                <version>${redis.version}</version>
            </dependency>
            <dependency>
                <groupId>com.yj2025</groupId>
                <artifactId>redis-spring-boot-starter</artifactId>
                <version>${redis.version}</version>
            </dependency>

            <!-- websocket -->
            <dependency>
                <groupId>com.yj2025</groupId>
                <artifactId>websocket-spring-boot-autoconfigure</artifactId>
                <version>${websocket.version}</version>
            </dependency>
            <dependency>
                <groupId>com.yj2025</groupId>
                <artifactId>websocket-spring-boot-starter</artifactId>
                <version>${websocket.version}</version>
            </dependency>

            <!-- audit -->
            <dependency>
                <groupId>com.yj2025</groupId>
                <artifactId>audit-spring-boot-autoconfigure</artifactId>
                <version>${audit.version}</version>
            </dependency>
            <dependency>
                <groupId>com.yj2025</groupId>
                <artifactId>audit-spring-boot-starter</artifactId>
                <version>${audit.version}</version>
            </dependency>

            <!-- doc -->
            <dependency>
                <groupId>com.yj2025</groupId>
                <artifactId>doc-spring-boot-autoconfigure</artifactId>
                <version>${doc.version}</version>
            </dependency>
            <dependency>
                <groupId>com.yj2025</groupId>
                <artifactId>doc-spring-boot-starter</artifactId>
                <version>${doc.version}</version>
            </dependency>

            <!-- mvc exception -->
            <dependency>
                <groupId>com.yj2025</groupId>
                <artifactId>mvc-rest-spring-boot-autoconfigure</artifactId>
                <version>${mvc-rest.version}</version>
            </dependency>
            <dependency>
                <groupId>com.yj2025</groupId>
                <artifactId>mvc-rest-spring-boot-starter</artifactId>
                <version>${mvc-rest.version}</version>
            </dependency>

            <!-- lock -->
            <dependency>
                <groupId>com.yj2025</groupId>
                <artifactId>lock-spring-boot-autoconfigure</artifactId>
                <version>${lock.version}</version>
            </dependency>
            <dependency>
                <groupId>com.yj2025</groupId>
                <artifactId>lock-spring-boot-starter</artifactId>
                <version>${lock.version}</version>
            </dependency>

            <!-- override -->
            <dependency>
                <groupId>com.yj2025</groupId>
                <artifactId>customizer-spring-boot-autoconfigure</artifactId>
                <version>${override.version}</version>
            </dependency>
            <dependency>
                <groupId>com.yj2025</groupId>
                <artifactId>customizer-spring-boot-starter</artifactId>
                <version>${override.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>


    <repositories>
        <repository>
            <id>nexus</id>
            <url>http://192.168.1.235:8081/nexus/content/groups/public/</url>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <id>spring-snapshots</id>
            <url>https://repo.spring.io/snapshot</url>
        </pluginRepository>
        <pluginRepository>
            <id>spring-milestones</id>
            <url>https://repo.spring.io/milestone</url>
        </pluginRepository>
    </pluginRepositories>

    <distributionManagement>
        <repository>
            <id>releases</id>
            <name>Nexus Release Repository</name>
            <url>http://192.168.1.235:8081/nexus/content/repositories/releases/</url>
        </repository>
        <snapshotRepository>
            <id>snapshots</id>
            <name>Nexus Snapshot Repository</name>
            <url>http://192.168.1.235:8081/nexus/content/repositories/snapshots/</url>
        </snapshotRepository>
    </distributionManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>${maven-source-plugin.version}</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>${maven-javadoc-plugin.version}</version>
                <configuration>
                    <show>private</show>
                    <nohelp>true</nohelp>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven-surefire-plugin.version}</version>
                <configuration>
                    <skipTests>true</skipTests>
                </configuration>
            </plugin>

        </plugins>
    </build>


</project>
