spring.application.name=sms-spring-boot-sample
# sms ????????
sms.type=mchuan
sms.audit.exchange=platform
sms.audit.routing-key=platform.mchuan.sms.record


# alidayu
alidayu.sms.http-url=http://gw.api.taobao.com/router/rest
alidayu.sms.app-key=YOUR_APP_KEY
alidayu.sms.app-secret=YOUR_APP_SECRET
alidayu.sms.connect-timeout=15000
alidayu.sms.read-timeout=30000

# mchuan
mchuan.sms.http-url=http://YOUR_SMS_SERVER_IP:8002/sms3_api/jsonapi/jsonrpc2.jsp
mchuan.sms.userid=202262
mchuan.sms.password=YOUR_PASSWORD
mchuan.sms.connect-timeout=15000
mchuan.sms.read-timeout=30000
mchuan.sms.write-timeout=15000


# rabbitmq
spring.rabbitmq.host=10.96.92.26
spring.rabbitmq.port=5672
spring.rabbitmq.username=rabbit
spring.rabbitmq.password=123456

# redis
spring.redis.port=6379
spring.redis.host=10.96.185.218
