spring.profiles.active=test
doc.head.wrap.enabled=false
spring.main.allow-bean-definition-overriding=true

# override kotime
#override.ko-time.enable=false
#override.ko-time.pointcut=execution(public * com.github..*.*(..))
#server.shutdown=graceful
