spring.profiles.active=test
doc.head.wrap.enabled=false


# override kotime
#override.ko-time.enable=false
#override.ko-time.pointcut=execution(public * com.github..*.*(..))
#server.shutdown=graceful
