spring.rabbitmq.host=10.96.128.61
spring.rabbitmq.username=yunji
spring.rabbitmq.password=123456

audit.type=rabbit
audit.rabbit.exchange=test
audit.rabbit.routing-key=test.audit

spring.application.name=audit-spring-boot-sample
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
#management.endpoint.logfile.external-file=/data/java/logs/${spring.application.name}.log
management.metrics.tags.profile=test
management.metrics.tags.application=${spring.application.name}
