### 获取token
POST http://localhost:8088/oauth/token
Content-Type: application/json

{
  "username": "ierp",
  "password": "123456"
}

### 刷新token,切换用户
POST http://localhost:8088/oauth/refresh
Content-Type: application/json

{
  "usercode": "jsjfff",
  "refresh_token": "e27e332f-f6af-44ea-8bb5-748c291e5304"
}

### 注销token 方式一
GET http://localhost:8088/oauth/revoke
Authorization: Bearer b9e5fcf9-1e77-43d2-8ad1-0b082bd54404
Accept: application/json

### 注销token 方式二
GET http://localhost:8088/oauth/revoke?access_token=db82815f-7969-46a1-8069-be8fae9d9c85
Accept: application/json