spring.application.name=job-sample
# xxl job center
### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl.job.admin.addresses=http://10.96.219.246
#xxl.job.admin.addresses=http://localhost:8080

### xxl-job, access token
#xxl.job.accessToken=

### xxl-job executor appname
xxl.job.executor.appname=${spring.application.name}
### xxl-job executor registry-address: default use address to registry , otherwise use ip:port if address is null
#xxl.job.executor.address=192.168.1.90:8080
### xxl-job executor server-info
#xxl.job.executor.ip=192.168.1.90
xxl.job.executor.port=9999
### xxl-job executor log-path
xxl.job.executor.logpath=/data/java/logs/jobhandler
### xxl-job executor log-retention-days
xxl.job.executor.logretentiondays=30
