spring.datasource.dynamic.primary=master
spring.datasource.dynamic.strict=false
spring.datasource.type=com.zaxxer.hikari.HikariDataSource

spring.datasource.dynamic.datasource.master.url=jdbc:mysql://10.96.15.155:3306/storehouse?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
spring.datasource.dynamic.datasource.master.username=yunji
spring.datasource.dynamic.datasource.master.password=123456
spring.datasource.dynamic.datasource.master.pool-name=HikariPool-master
spring.datasource.dynamic.datasource.master.hikari.maximum-pool-size=200
spring.datasource.dynamic.datasource.master.hikari.minimum-idle=10
spring.datasource.dynamic.datasource.master.hikari.idle-timeout=600000
spring.datasource.dynamic.datasource.master.hikari.is-auto-commit=true
spring.datasource.dynamic.datasource.master.hikari.max-lifetime=1800000
spring.datasource.dynamic.datasource.master.hikari.connection-timeout=30000

spring.datasource.dynamic.datasource.read.url=jdbc:mysql://10.96.15.155:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
spring.datasource.dynamic.datasource.read.username=yunji
spring.datasource.dynamic.datasource.read.password=123456
spring.datasource.dynamic.datasource.read.pool-name=HikariPool-read
spring.datasource.dynamic.datasource.read.hikari.maximum-pool-size=200
spring.datasource.dynamic.datasource.read.hikari.minimum-idle=10
spring.datasource.dynamic.datasource.read.hikari.idle-timeout=600000
spring.datasource.dynamic.datasource.read.hikari.is-auto-commit=true
spring.datasource.dynamic.datasource.read.hikari.max-lifetime=1800000
spring.datasource.dynamic.datasource.read.hikari.connection-timeout=30000


spring.datasource.tenant.datasource.sharding001.url=jdbc:mysql://10.96.15.155:3306/bboss?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
spring.datasource.tenant.datasource.sharding001.username=yunji
spring.datasource.tenant.datasource.sharding001.password=123456
spring.datasource.tenant.datasource.sharding001.pool-name=sharding001
spring.datasource.tenant.datasource.sharding001.hikari.maximum-pool-size=20
spring.datasource.tenant.datasource.sharding001.hikari.minimum-idle=10
spring.datasource.tenant.datasource.sharding001.hikari.idle-timeout=600000
spring.datasource.tenant.datasource.sharding001.hikari.is-auto-commit=true
spring.datasource.tenant.datasource.sharding001.hikari.max-lifetime=1800000
spring.datasource.tenant.datasource.sharding001.hikari.connection-timeout=30000