# fileupload
#access key
file.storage.access-key=azamk57pyFWNZY3DZQYQnKZkRsC2k3FfD8hZFVEz
#secret key
file.storage.secret-key=0vp7FYYy2kbbk0F9rWunv2tvqttQl1N7zO27TC5M
file.storage.upload-by-https=false
file.storage.region=z2
file.storage.file-record-directory=${user.home}/.file-upload-record
file.storage.put-threshold=4194304
file.storage.connect-timeout=10
file.storage.write-timeout=0
file.storage.response-timeout=30
file.storage.max-retry-times=5

file.storage.buckets.default_public_bucket.isDefault=true
file.storage.buckets.default_public_bucket.isPublic=true
file.storage.buckets.default_public_bucket.bucketName=sz-yunji-test
file.storage.buckets.default_public_bucket.domain=tfile.yj2025.com

file.storage.buckets.default_private_bucket.isDefault=true
file.storage.buckets.default_private_bucket.isPublic=false
file.storage.buckets.default_private_bucket.bucketName=sz-yunji-test-private
file.storage.buckets.default_private_bucket.domain=ptfile.yj2025.com