# fileupload
#access key
file.storage.access-key=YOUR_ACCESS_KEY
#secret key
file.storage.secret-key=YOUR_SECRET_KEY
file.storage.upload-by-https=false
file.storage.region=z2
file.storage.file-record-directory=${user.home}/.file-upload-record
file.storage.put-threshold=4194304
file.storage.connect-timeout=10
file.storage.write-timeout=0
file.storage.response-timeout=30
file.storage.max-retry-times=5

file.storage.enable-dynamic-bucket=true
file.storage.dynamic-bucket-domain-suffix=.yj2025.com
file.storage.dynamic-bucket-use-https=true

file.storage.buckets.default_public_bucket.isDefault=true
file.storage.buckets.default_public_bucket.isPublic=true
file.storage.buckets.default_public_bucket.bucketName=sz-yunji-test
file.storage.buckets.default_public_bucket.domain=tfile.yj2025.com

file.storage.buckets.default_private_bucket.isDefault=true
file.storage.buckets.default_private_bucket.isPublic=false
file.storage.buckets.default_private_bucket.bucketName=sz-yunji-test-private
file.storage.buckets.default_private_bucket.domain=ptfile.yj2025.com


## erp fileStorage??
file.storage.product.erp.access-key=YOUR_ACCESS_KEY
file.storage.product.erp.secret-key=YOUR_SECRET_KEY
file.storage.product.erp.upload-by-https=false
file.storage.product.erp.region=z2
file.storage.product.erp.file-record-directory=${user.home}/.file-upload-record
file.storage.product.erp.put-threshold=4194304
file.storage.product.erp.connect-timeout=10
file.storage.product.erp.write-timeout=0
file.storage.product.erp.response-timeout=30
file.storage.product.erp.max-retry-times=5
file.storage.product.erp.enable-dynamic-bucket=true
file.storage.product.erp.dynamic-bucket-domain-suffix=.yj2025.com
file.storage.product.erp.dynamic-bucket-use-https=true
file.storage.product.erp.buckets.default_public_bucket.isDefault=true
file.storage.product.erp.buckets.default_public_bucket.isPublic=true
file.storage.product.erp.buckets.default_public_bucket.bucketName=sz-yunji-test
file.storage.product.erp.buckets.default_public_bucket.domain=tfile.yj2025.com
file.storage.product.erp.buckets.default_private_bucket.isDefault=true
file.storage.product.erp.buckets.default_private_bucket.isPublic=false
file.storage.product.erp.buckets.default_private_bucket.bucketName=sz-yunji-test-private
file.storage.product.erp.buckets.default_private_bucket.domain=ptfile.yj2025.com

## platform??
file.storage.product.platform.access-key=YOUR_ACCESS_KEY
file.storage.product.platform.secret-key=YOUR_SECRET_KEY
file.storage.product.platform.upload-by-https=false
file.storage.product.platform.region=z2
file.storage.product.platform.file-record-directory=${user.home}/.file-upload-record
file.storage.product.platform.put-threshold=4194304
file.storage.product.platform.connect-timeout=10
file.storage.product.platform.write-timeout=0
file.storage.product.platform.response-timeout=30
file.storage.product.platform.max-retry-times=5
file.storage.product.platform.enable-dynamic-bucket=true
file.storage.product.platform.dynamic-bucket-domain-suffix=.yj2025.com
file.storage.product.platform.dynamic-bucket-use-https=true
file.storage.product.platform.buckets.default_public_bucket.isDefault=true
file.storage.product.platform.buckets.default_public_bucket.isPublic=true
file.storage.product.platform.buckets.default_public_bucket.bucketName=sz-yunji-test
file.storage.product.platform.buckets.default_public_bucket.domain=tfile.yj2025.com
file.storage.product.platform.buckets.default_private_bucket.isDefault=true
file.storage.product.platform.buckets.default_private_bucket.isPublic=false
file.storage.product.platform.buckets.default_private_bucket.bucketName=sz-yunji-test-private
file.storage.product.platform.buckets.default_private_bucket.domain=ptfile.yj2025.com

## ec??
file.storage.product.ec.access-key=YOUR_ACCESS_KEY
file.storage.product.ec.secret-key=YOUR_SECRET_KEY
file.storage.product.ec.upload-by-https=false
file.storage.product.ec.region=z2
file.storage.product.ec.file-record-directory=${user.home}/.file-upload-record
file.storage.product.ec.put-threshold=4194304
file.storage.product.ec.connect-timeout=10
file.storage.product.ec.write-timeout=0
file.storage.product.ec.response-timeout=30
file.storage.product.ec.max-retry-times=5
file.storage.product.ec.enable-dynamic-bucket=true
file.storage.product.ec.dynamic-bucket-domain-suffix=.yj2025.com
file.storage.product.ec.dynamic-bucket-use-https=true
file.storage.product.ec.buckets.default_public_bucket.isDefault=true
file.storage.product.ec.buckets.default_public_bucket.isPublic=true
file.storage.product.ec.buckets.default_public_bucket.bucketName=sz-yunji-test
file.storage.product.ec.buckets.default_public_bucket.domain=tfile.yj2025.com
file.storage.product.ec.buckets.default_private_bucket.isDefault=true
file.storage.product.ec.buckets.default_private_bucket.isPublic=false
file.storage.product.ec.buckets.default_private_bucket.bucketName=sz-yunji-test-private
file.storage.product.ec.buckets.default_private_bucket.domain=ptfile.yj2025.com

## p3??
file.storage.product.p3.access-key=YOUR_ACCESS_KEY
file.storage.product.p3.secret-key=YOUR_SECRET_KEY
file.storage.product.p3.upload-by-https=false
file.storage.product.p3.region=z2
file.storage.product.p3.file-record-directory=${user.home}/.file-upload-record
file.storage.product.p3.put-threshold=4194304
file.storage.product.p3.connect-timeout=10
file.storage.product.p3.write-timeout=0
file.storage.product.p3.response-timeout=30
file.storage.product.p3.max-retry-times=5
file.storage.product.p3.enable-dynamic-bucket=true
file.storage.product.p3.dynamic-bucket-domain-suffix=.yj2025.com
file.storage.product.p3.dynamic-bucket-use-https=true
file.storage.product.p3.buckets.default_public_bucket.isDefault=true
file.storage.product.p3.buckets.default_public_bucket.isPublic=true
file.storage.product.p3.buckets.default_public_bucket.bucketName=sz-yunji-test
file.storage.product.p3.buckets.default_public_bucket.domain=tfile.yj2025.com
file.storage.product.p3.buckets.default_private_bucket.isDefault=true
file.storage.product.p3.buckets.default_private_bucket.isPublic=false
file.storage.product.p3.buckets.default_private_bucket.bucketName=sz-yunji-test-private
file.storage.product.p3.buckets.default_private_bucket.domain=ptfile.yj2025.com

## scm??
file.storage.product.scm.access-key=YOUR_ACCESS_KEY
file.storage.product.scm.secret-key=YOUR_SECRET_KEY
file.storage.product.scm.upload-by-https=false
file.storage.product.scm.region=z2
file.storage.product.scm.file-record-directory=${user.home}/.file-upload-record
file.storage.product.scm.put-threshold=4194304
file.storage.product.scm.connect-timeout=10
file.storage.product.scm.write-timeout=0
file.storage.product.scm.response-timeout=30
file.storage.product.scm.max-retry-times=5
file.storage.product.scm.enable-dynamic-bucket=true
file.storage.product.scm.dynamic-bucket-domain-suffix=.yj2025.com
file.storage.product.scm.dynamic-bucket-use-https=true
file.storage.product.scm.buckets.default_public_bucket.isDefault=true
file.storage.product.scm.buckets.default_public_bucket.isPublic=true
file.storage.product.scm.buckets.default_public_bucket.bucketName=sz-yunji-test
file.storage.product.scm.buckets.default_public_bucket.domain=tfile.yj2025.com
file.storage.product.scm.buckets.default_private_bucket.isDefault=true
file.storage.product.scm.buckets.default_private_bucket.isPublic=false
file.storage.product.scm.buckets.default_private_bucket.bucketName=sz-yunji-test-private
file.storage.product.scm.buckets.default_private_bucket.domain=ptfile.yj2025.com