spring.rabbitmq.host=10.96.128.61
spring.rabbitmq.username=yunji
spring.rabbitmq.password=123456

# 开启重试
spring.rabbitmq.listener.simple.retry.enabled=true
# 最大重试次数
spring.rabbitmq.listener.simple.retry.max-attempts=3
# 第一次和第二次间隔时间
spring.rabbitmq.listener.simple.retry.initial-interval=1000
# 重试间隔时间的乘数
spring.rabbitmq.listener.simple.retry.multiplier=5
# 最大间隔时间
spring.rabbitmq.listener.simple.retry.max-interval=10000
# 线程池消费
spring.rabbitmq.listener.simple.concurrency=3
# 线程池消费 最大线程数
spring.rabbitmq.listener.simple.max-concurrency=5

audit.type=rabbit
audit.rabbit.exchange=test
audit.rabbit.routing-key=test.audit

spring.application.name=audit-spring-boot-sample
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
#management.endpoint.logfile.external-file=/data/java/logs/${spring.application.name}.log
management.metrics.tags.profile=test
management.metrics.tags.application=${spring.application.name}
