spring.redis.database=0
spring.redis.host=10.96.185.218
spring.redis.port=6379
spring.redis.lettuce.pool.max-idle=500
spring.redis.lettuce.pool.min-idle=50
spring.redis.lettuce.pool.max-wait=-1s
spring.redis.lettuce.pool.max-active=-1

# ??????id
oauth2.server.client-id=ierp
# ?????
oauth2.server.client-secret=123456
# ???url
oauth2.server.redirect-uri=https://yj2025.com
# access_token ???????
oauth2.server.access-token-validity-seconds=7200
# refresh_token ???????
oauth2.server.refresh-token-validity-seconds=86400
# ??????url????access_token???????
oauth2.server.allow-uri-token=true
# ????jwt??
oauth2.server.jwt.enabled=false
# jwt??
oauth2.server.jwt.key-file=classpath:jwt.jks
# jwt????
oauth2.server.jwt.key-alias=jwt
# jwt????
oauth2.server.jwt.key-password=123456