spring.redis.database=0
spring.redis.host=10.96.185.218
spring.redis.port=6379
spring.redis.lettuce.pool.max-idle=500
spring.redis.lettuce.pool.min-idle=50
spring.redis.lettuce.pool.max-wait=-1s
spring.redis.lettuce.pool.max-active=-1

oauth2.server.jwt.enabled=false
oauth2.server.jwt.key-file=classpath:jwt.jks
oauth2.server.jwt.key-alias=jwt
oauth2.server.jwt.key-password=123456