### 获取token
POST http://localhost:8080/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=ierp&client_secret=123456&username=test&password=123456

### 注销token 方式一
GET http://localhost:8080/oauth/revoke
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50Q29kZSI6bnVsbCwiZW50TmFtZSI6bnVsbCwiZW50Q29kZSI6bnVsbCwiYWNjb3VudE5hbWUiOiJ0ZXN0IiwidXNlcl9uYW1lIjoidGVzdCIsInNjb3BlIjpbImFsbCJdLCJzZXJ2ZXJUaW1lIjoxNjUyMTQ2NTY5LCJleHAiOjE2NTIxNTM3NjksInVzZXJOYW1lIjpudWxsLCJqdGkiOiIyYjRlZmUwMC04NzM3LTRkYmUtYWNjMS02ZjRhNGY1MzJlMTIiLCJ1c2VyQ29kZSI6bnVsbCwiY2xpZW50X2lkIjoiaWVycCJ9.LgkJe6hTNOfzRfMOrWj5gjAh2UIggZ0lMKxs-Avw9p5BBvXR01aRKrEmMUnDiFOmCXx9buVOfz_l80w4O6x2ai2wg5WF0sLYm3fxIHV5aHmvhOjq7GHtk_GJ3rKtkHdrZ-_MuHpnZgNC059BaQkStGbQpbRFKJ6BvXdxWFha_3tlb14KnvIXraFC3jSGuEt3_E4mf5Kn2NuNE7eCMDXDVSBxIesmc3QvsU3AE4po-OQeBKq_Mj_MYW8u80d2mEhGEwHzMaLXpPt_6MOpaOytt48Fb2n0Y8f7SUugUgAroWpvZvX_gjBHNqWeN9u7OyVce9VMUcYljdknH9SQZ9k6eg
Accept: application/json

### 注销token 方式二
GET http://localhost:8080/oauth/revoke?access_token=5fe1aa09-2c58-4dcc-823b-fa9791daaea5
Accept: application/json