spring.rabbitmq.host=10.96.92.26
spring.rabbitmq.username=yunji
spring.rabbitmq.password=123456
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=1000
spring.rabbitmq.listener.simple.retry.multiplier=5
spring.rabbitmq.listener.simple.retry.max-interval=10000
spring.rabbitmq.listener.simple.concurrency=5
spring.rabbitmq.listener.simple.max-concurrency=10
