### 获取token
POST http://localhost:8088/oauth/token
Content-Type: application/json

{
  "username": "test",
  "password": "123456"
}

### 刷新token,切换用户
POST http://localhost:8088/oauth/refresh
Content-Type: application/json

{
  "usercode": "aaabbb",
  "refresh_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50Q29kZSI6bnVsbCwiZW50TmFtZSI6bnVsbCwiYWNjb3VudE5hbWUiOiJ0ZXN0IiwidXNlcl9uYW1lIjoidGVzdCIsInVzZXJOYW1lIjpudWxsLCJ1c2VyQ29kZSI6bnVsbCwiY2xpZW50X2lkIjoiaWVycCIsImVudENvZGUiOm51bGwsInNjb3BlIjpbImFsbCJdLCJhdGkiOiI5MGUyOGU0MC1iZTUwLTQ4OGMtOThkMC1hZjk0NzY4Yjk2ZjQiLCJzZXJ2ZXJUaW1lIjoxNjUyMjQ5Nzg3LCJleHAiOjE2NTIzMzYxODcsImp0aSI6IjVlNWEzOTBmLTdhODAtNGY1Zi04N2M4LTcwMjJlYjJkY2NkNSJ9.JhdVBEf1fSaQByfgd4JkwZq1dQYKWXIU_FIoaeBfA5M0Fi70scdERsMiZRDyGy83MJILkzfeg1_ZyQOYjqdnj4J0QwOAKFgL0tbLgHmP41BobZ9frkpWdO6hpBpXoCdDyN7isVgY5CWfWtrNHY2aUlaco_90s00BS17bL-qErAMT6S7wRE51MHhFKF637hfnDqq024TYY93a8NyISzlKZ_WRp-Q8JwTOeRz_gPuYHyvSSiP6SzZV0YAIJRc2TMFdmgT7wPtb5vXIwTwp_8TWHs_-k2uyR4umZ0nbWQdII2AMI8oAcbV5DLd35vsuiPcNVb_QTk6K827KF6fe00RDSw"
}

### 注销token 方式一
GET http://localhost:8088/oauth/revoke
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50Q29kZSI6bnVsbCwiZW50TmFtZSI6bnVsbCwiZW50Q29kZSI6bnVsbCwiYWNjb3VudE5hbWUiOiJhYWFiYmIwMDEiLCJ1c2VyX25hbWUiOiJhYWFiYmIwMDEiLCJzY29wZSI6WyJhbGwiXSwic2VydmVyVGltZSI6MTY1MjI1MDQzMSwiZXhwIjoxNjUyMjU3NjMxLCJ1c2VyTmFtZSI6bnVsbCwianRpIjoiZDBjZTI2MWQtOWMwYS00ZmNhLTgyMmUtYzY1MmYxZmNlZDg4IiwidXNlckNvZGUiOm51bGwsImNsaWVudF9pZCI6ImllcnAifQ.HwnniQhOvCDl86c2cZGTMPtiGNJT82OBwlvzWiEDVANbe2zTTPZ0JV1Tdx0jIa_wlvJF95ReJST2byERUybUOWlWZeKOgmL5SUQYqwqVLN7LyHQlBnrWJp0GocA1O8wwukp0IynPFMOVsgvyndvyxkVhTjtDCp2_EYsPB4L6YjF3ru14Hrbp61ZvGrJqeTYZLHO37pXa_UR1Njb0-gVi4lKfGwq402ew_Z3PIGpqF52xWfPPfj7uFYuKeWEb83AgzMCP8q-uV6Kxnwgzoz2_oGk_nEnJDy4fgCN6bMGJUE_v8uGmhoNjknTTLVaMrzufrLDPiI5oeUxv1D-VWM5L8A
Accept: application/json

### 注销token 方式二
GET http://localhost:8088/oauth/revoke?access_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50Q29kZSI6bnVsbCwiZW50TmFtZSI6bnVsbCwiZW50Q29kZSI6bnVsbCwiYWNjb3VudE5hbWUiOiJqc2pmZmYwMDEiLCJ1c2VyX25hbWUiOiJqc2pmZmYwMDEiLCJzY29wZSI6WyJhbGwiXSwic2VydmVyVGltZSI6MTY1MjIzNjcxMCwiZXhwIjoxNjUyMjQzOTEwLCJ1c2VyTmFtZSI6bnVsbCwianRpIjoiYzIzODE0ZjgtNmZhMy00MDEwLWE2OWYtZDc5ZTg0NjNkNWY2IiwidXNlckNvZGUiOm51bGwsImNsaWVudF9pZCI6ImllcnAifQ.O3hatAkdLcdqCaYZ7s6vn4auMNOeCoKg6onA9AWF6TPG9MlAR81H3Setp9PyYjyWhDmjiePjhYTkgoGvc92RX9tpd8V7Nwyxr3je_zvNGmoWvW-bly3PxtY_IjeRWAnLL2nsnPMk4WI5fqORH0nvW2qLLng_cXGJd1q7X1OIH6pxewG2P636n1yXEFFuOF-WpEL-tI2rBagKAl-WnBn5PqTwcqMv7m6TnjIDp5DWevnlG8uJ_DaTKGeu7FlHOCdLZ0zn1B8hxs12wmKYpoBkmIJe8MOvYLECoSuuW1croP-mxASNXJGIXY5alhAuZci8ZMPg68qFttEoimViiQqRbg
Accept: application/json

### 测试白名单
GET http://localhost:8088/test
Accept: application/json

### 测试白名单，附带用户身份
GET http://localhost:8088/test?access_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50Q29kZSI6bnVsbCwiZW50TmFtZSI6bnVsbCwiZW50Q29kZSI6bnVsbCwiYWNjb3VudE5hbWUiOiJqc2pmZmYwMDEiLCJ1c2VyX25hbWUiOiJqc2pmZmYwMDEiLCJzY29wZSI6WyJhbGwiXSwic2VydmVyVGltZSI6MTY1MjIzNjcxMCwiZXhwIjoxNjUyMjQzOTEwLCJ1c2VyTmFtZSI6bnVsbCwianRpIjoiYzIzODE0ZjgtNmZhMy00MDEwLWE2OWYtZDc5ZTg0NjNkNWY2IiwidXNlckNvZGUiOm51bGwsImNsaWVudF9pZCI6ImllcnAifQ.O3hatAkdLcdqCaYZ7s6vn4auMNOeCoKg6onA9AWF6TPG9MlAR81H3Setp9PyYjyWhDmjiePjhYTkgoGvc92RX9tpd8V7Nwyxr3je_zvNGmoWvW-bly3PxtY_IjeRWAnLL2nsnPMk4WI5fqORH0nvW2qLLng_cXGJd1q7X1OIH6pxewG2P636n1yXEFFuOF-WpEL-tI2rBagKAl-WnBn5PqTwcqMv7m6TnjIDp5DWevnlG8uJ_DaTKGeu7FlHOCdLZ0zn1B8hxs12wmKYpoBkmIJe8MOvYLECoSuuW1croP-mxASNXJGIXY5alhAuZci8ZMPg68qFttEoimViiQqRbg
Accept: application/json

### 获取公钥
GET http://localhost:8088/oauth/token_key
Accept: application/json