spring.application.name=kafka-spring-boot-sample
spring.kafka.producer.client-id=${spring.application.name}
spring.kafka.producer.bootstrap-servers=10.100.48.151:9092,10.100.53.117:9092,10.100.93.168:9092
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer