# application
spring.application.name=kafka-spring-boot-sample

# kafka

# producer
spring.kafka.producer.client-id=scm-${spring.application.name}
spring.kafka.producer.bootstrap-servers=192.168.1.226:32192, 192.168.1.217:32292, 192.168.1.205:32392
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# consumer
spring.kafka.consumer.bootstrap-servers=192.168.1.226:32192, 192.168.1.217:32292, 192.168.1.205:32392
spring.kafka.consumer.client-id=scm-${spring.application.name}
spring.kafka.consumer.group-id=scm-${spring.kafka.consumer.client-id}
spring.kafka.consumer.enable-auto-commit=true
spring.kafka.listener.client-id=scm-${spring.application.name}
spring.kafka.listener.ack-mode=record
spring.kafka.listener.concurrency=3