spring.data.redis.database=0
spring.data.redis.host=10.96.94.119
spring.data.redis.port=6379
spring.data.redis.lettuce.pool.max-idle=500
spring.data.redis.lettuce.pool.min-idle=50
spring.data.redis.lettuce.pool.max-wait=-1s
spring.data.redis.lettuce.pool.max-active=-1

spring.rabbitmq.host=10.96.128.61
spring.rabbitmq.username=yunji
spring.rabbitmq.password=123456

websocket.server.port=8066
websocket.type=rabbit
websocket.rabbit.exchange=ierp
websocket.rabbit.routing-key=websocket