spring.rabbitmq.host=10.96.128.61
spring.rabbitmq.username=yunji
spring.rabbitmq.password=123456

websocket.producer.type=rabbit
websocket.producer.rabbit.exchange=ierp
websocket.producer.rabbit.routing-key=websocket